server:
  port: 4000

# Database connection
spring:
  datasource:
    url: jdbc:mysql://localhost/crm_clientes?useSSL=false&serverTimezone=UTC&
    dbname: crm_clientes
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

# Logs about SQL
loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

